codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 2

comment:
  require_changes: true
  after_n_builds: 2

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%