codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 46%
        threshold: 5%

comment:
  layout: "diff"
  behavior: default