// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputConfig } from "./InputConfig";
import type { OutputConfig } from "./OutputConfig";

export interface Config { input: InputConfig, output: OutputConfig, }