// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HighlightRange } from "./HighlightRange";

export interface Excerpt { text: string, highlight_ranges: Array<HighlightRange>, score: number, url_suffix: string | null, }