// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Filetype } from "./Filetype";
import type { FrontmatterConfig } from "./FrontmatterConfig";
import type { HTMLConfig } from "./HTMLConfig";
import type { SRTConfig } from "./SRTConfig";
import type { StemmingConfig } from "./StemmingConfig";

export interface File { title: string, url: string, fields: Record, contents: string | null, src_url: string | null, path: string | null, stemming: StemmingConfig | null, html_config: HTMLConfig | null, frontmatter_config: FrontmatterConfig | null, srt_config: SRTConfig | null, filetype: Filetype | null, }