// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface HTMLConfig { save_nearest_id: boolean, title_selector: string, included_selectors: Array<string>, excluded_selectors: Array<string>, }