// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { File } from "./File";
import type { FrontmatterConfig } from "./FrontmatterConfig";
import type { HTMLConfig } from "./HTMLConfig";
import type { SRTConfig } from "./SRTConfig";
import type { TitleBoost } from "./TitleBoost";

export interface InputConfig { base_directory: string, url_prefix: string, files: Array<File>, title_boost: TitleBoost, html_config: HTMLConfig, frontmatter_config: FrontmatterConfig, srt_config: SRTConfig, }