// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Document } from "./Document";
import type { Excerpt } from "./Excerpt";
import type { HighlightRange } from "./HighlightRange";

export interface SearchResult { entry: Document, excerpts: Array<Excerpt>, title_highlight_ranges: Array<HighlightRange>, score: number, }