// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchResult } from "./SearchResult";

export interface SearchOutput { results: Array<SearchResult>, total_hit_count: number, url_prefix: string, }