// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SRTTimestampFormat } from "./SRTTimestampFormat";

export interface SRTConfig { timestamp_linking: boolean, timestamp_template_string: string, timestamp_format: SRTTimestampFormat, }