[package]
name = "stork-config"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-stemmers = "1.2.0"
serde = { version = "1.0.130", features = ["derive"] }
smart-default = "0.6.0"
thiserror = "1.0.29"
toml = "0.5.8"

[dev-dependencies]
pretty_assertions = "1.0.0"
