on: workflow_dispatch
name: "Manually Build Artifact"
jobs:
  build_ubuntu:
    name: "Build Artifact (Ubuntu 16.04)"
    runs-on: "ubuntu-16.04"
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Federalist Papers Repository
        uses: actions/checkout@v2
        with:
          repository: jameslittle230/federalist
          path: ./test/federalist
      - run: cargo install wasm-pack # Todo: Figure out if this is required or if I can download a binary
      - name: Build WASM
        run: wasm-pack build --target web --out-name stork  -- --no-default-features
      - name: Build executable
        run: cargo build --verbose --release
      - run: ls -al ./test/federalist-config
      - name: Build Federalist index file and move to ./dist
        run: cargo run -- build -i ./test/federalist-config/federalist.toml -o test/federalist.st && mkdir -p dist && cp test/*.st dist # Todo: Don't rebuild executable on this command
      - run: yarn install
      - run: yarn webpack --mode=production
      - name: Upload executable build artifact
        uses: actions/upload-artifact@v1
        with:
          name: stork-ubuntu-16-04
          path: ./target/release/stork
      - name: Upload JS/WASM artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist-directory
          path: ./dist/
